// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjzjhbcwljeuklncxwae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqempoYmN3bGpldWtsbmN4d2FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NzkwMjQsImV4cCI6MjA2MjE1NTAyNH0.QPMZQayipFbH2uZQWFFvGYljR7yNYAfhCZ1DGyPe0mk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);